[build]
  publish = "."
  ignore = "exit 0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200
